// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTcx returns the embedded CollectionSpec for tcx.
func loadTcx() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcxBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcx: %w", err)
	}

	return spec, err
}

// loadTcxObjects loads tcx and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcxObjects
//	*tcxPrograms
//	*tcxMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcxObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcx()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcxSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcxSpecs struct {
	tcxProgramSpecs
	tcxMapSpecs
	tcxVariableSpecs
}

// tcxProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcxProgramSpecs struct {
	NetkitPeer    *ebpf.ProgramSpec `ebpf:"netkit_peer"`
	NetkitPrimary *ebpf.ProgramSpec `ebpf:"netkit_primary"`
}

// tcxMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcxMapSpecs struct {
}

// tcxVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcxVariableSpecs struct {
	EgressPktCount  *ebpf.VariableSpec `ebpf:"egress_pkt_count"`
	IngressPktCount *ebpf.VariableSpec `ebpf:"ingress_pkt_count"`
}

// tcxObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcxObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcxObjects struct {
	tcxPrograms
	tcxMaps
	tcxVariables
}

func (o *tcxObjects) Close() error {
	return _TcxClose(
		&o.tcxPrograms,
		&o.tcxMaps,
	)
}

// tcxMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcxObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcxMaps struct {
}

func (m *tcxMaps) Close() error {
	return _TcxClose()
}

// tcxVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcxObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcxVariables struct {
	EgressPktCount  *ebpf.Variable `ebpf:"egress_pkt_count"`
	IngressPktCount *ebpf.Variable `ebpf:"ingress_pkt_count"`
}

// tcxPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcxObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcxPrograms struct {
	NetkitPeer    *ebpf.Program `ebpf:"netkit_peer"`
	NetkitPrimary *ebpf.Program `ebpf:"netkit_primary"`
}

func (p *tcxPrograms) Close() error {
	return _TcxClose(
		p.NetkitPeer,
		p.NetkitPrimary,
	)
}

func _TcxClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcx_bpfeb.o
var _TcxBytes []byte
