// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package objs

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type BpfIpInfo struct {
	Kind    uint8
	Mac     [6]uint8
	_       [1]byte
	Ifindex uint32
}

type BpfNatKey struct {
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
	Proto   uint8
	_       [3]byte
}

type BpfNatValue struct {
	NewSrcIp   uint32
	NewSrcPort uint16
	_          [2]byte
}

type BpfQnameKey struct{ Qname [256]uint8 }

type BpfSockKey struct {
	RemoteIp4  uint32
	LocalIp4   uint32
	RemotePort uint32
	LocalPort  uint32
	Family     uint32
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	ExternalTcxEgress  *ebpf.ProgramSpec `ebpf:"external_tcx_egress"`
	ExternalTcxIngress *ebpf.ProgramSpec `ebpf:"external_tcx_ingress"`
	NetkitPeer         *ebpf.ProgramSpec `ebpf:"netkit_peer"`
	NetkitPrimary      *ebpf.ProgramSpec `ebpf:"netkit_primary"`
	ProgMsgVerdict     *ebpf.ProgramSpec `ebpf:"prog_msg_verdict"`
	SockopsLogger      *ebpf.ProgramSpec `ebpf:"sockops_logger"`
	TapTcxEgress       *ebpf.ProgramSpec `ebpf:"tap_tcx_egress"`
	TapTcxIngress      *ebpf.ProgramSpec `ebpf:"tap_tcx_ingress"`
	XdpProg            *ebpf.ProgramSpec `ebpf:"xdp_prog"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	IpInfo   *ebpf.MapSpec `ebpf:"ip_info"`
	NatTable *ebpf.MapSpec `ebpf:"nat_table"`
	QnameMap *ebpf.MapSpec `ebpf:"qname_map"`
	Sockhash *ebpf.MapSpec `ebpf:"sockhash"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	DefaultMac *ebpf.VariableSpec `ebpf:"default_mac"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	IpInfo   *ebpf.Map `ebpf:"ip_info"`
	NatTable *ebpf.Map `ebpf:"nat_table"`
	QnameMap *ebpf.Map `ebpf:"qname_map"`
	Sockhash *ebpf.Map `ebpf:"sockhash"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.IpInfo,
		m.NatTable,
		m.QnameMap,
		m.Sockhash,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	DefaultMac *ebpf.Variable `ebpf:"default_mac"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	ExternalTcxEgress  *ebpf.Program `ebpf:"external_tcx_egress"`
	ExternalTcxIngress *ebpf.Program `ebpf:"external_tcx_ingress"`
	NetkitPeer         *ebpf.Program `ebpf:"netkit_peer"`
	NetkitPrimary      *ebpf.Program `ebpf:"netkit_primary"`
	ProgMsgVerdict     *ebpf.Program `ebpf:"prog_msg_verdict"`
	SockopsLogger      *ebpf.Program `ebpf:"sockops_logger"`
	TapTcxEgress       *ebpf.Program `ebpf:"tap_tcx_egress"`
	TapTcxIngress      *ebpf.Program `ebpf:"tap_tcx_ingress"`
	XdpProg            *ebpf.Program `ebpf:"xdp_prog"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.ExternalTcxEgress,
		p.ExternalTcxIngress,
		p.NetkitPeer,
		p.NetkitPrimary,
		p.ProgMsgVerdict,
		p.SockopsLogger,
		p.TapTcxEgress,
		p.TapTcxIngress,
		p.XdpProg,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
